apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordscontainer
  labels:
    app: ordscontainer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ordscontainer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ordscontainer
    spec:
      containers:
        - name: ordscontainer
          image: ams.ocir.io/oraseemeadesandbox/publicrepo/oracle/restdataservices:20.4.3
          env:
          - name: ORACLE_USER
            value: "ORDS_CUSTOM"
          - name: ORACLE_SERVICE
            value: "repodb_medium"
          - name: CONTEXT_ROOT
            value: "ords"
          - name: ORACLE_PWD
            value: "dummy"
          - name: ORDS_PWD
            valueFrom:
              secretKeyRef:
                name: ordspassword
                key: password
          ports:
            - containerPort: 8888
      imagePullSecrets:
         - name: oke-registry-secret
---
apiVersion: v1
kind: Service
metadata:
 name: ordscontainer
spec:
 type: LoadBalancer
 selector:
   app: ordscontainer
 ports:
   - name: client
     protocol: TCP
     port: 8888
